### PR TITLE
feat: ability to handle async Ring requests

### PR DESCRIPTION
**Pull request by janosmeszaros**
`ring` supports async [handlers](https://github.com/ring-clojure/ring/wiki/Concepts) and this PR aims to handle these. 
Please review it and decide whether it makes sense to include this feature to the library.
Thanks

### CODE REVIEW

**Comment by MalloZup** [comment]
hi @janosmeszaros  thx for PR. 

Can you add use-cases and documentation inherent to this feature? thx.

A part of that we will need to clarify some things in short-term and then we can take look on this.
thx for your time invested. 

I will have look after the short-term tasks but You can add some documentation to your feature.

**Comment by janosmeszaros** [comment]
I'll add some documentation during the weekend 😉

**Comment by Kauko** [comment]
Would it be possible to move this forward? Edit: I don't mind working on this if that gets this merged.

**Comment by janosmeszaros** [comment]
@Kauko totally forgot about this, I've just fixed the merge conflicts.

@MalloZup could you please take another look at this?

**Comment by enspritz** [comment]
I'm also looking for exactly this. Can we get this merged and released? 🎉
ping @Kauko  @MalloZup  @slipset @janosmeszaros

**Pull request merged**
