### PR TITLE
Issue #11/clearing default registry

### PR DESCRIPTION
**Pull request by codification**
I added a simple test-case illustrating the issue as well as a workaround. Also added a caveat to the README.
Use if you like.

### CODE REVIEW

**Comment by codification** [comment]
Regarding #11

**Comment by marco-m** [comment]
@xsc any news about this PR ? Should it be accepted, modified or declined ?

**Comment by delitescere** [comment]
The problem is that things can register collectors with the default registry outside of the Iapetos lifecycle (e.g. log4j2).

The latest changes to Iapetos allow easy registering/de-registering (and clearing) of collectors Iapetos has handled. In no circumstances should Iapetos de-register or clear anything it hasn't registered.

If you're using something like Sierra's components life is now very good:

```clojure
(ns component.prometheus
  (:require [com.stuartsierra.component :refer [Lifecycle start stop]]
            [iapetos.core :as metrics]))

(defrecord Prometheus []
  Lifecycle

  (start [component]
    (-> component
      (assoc :registry ((apply comp (:metrics-collectors component)) metrics/default-registry))))

  (stop [component]
    (try
      (metrics/clear (:registry component))
      (catch Exception _))
    (-> component
      (assoc :metrics-collectors nil)
      (assoc :registry nil))))
```

Note the `metrics/default-registry` in the `start`, and the `metrics/clear` in the `stop`. 💯

**Comment by delitescere** [comment]
If you're using something like Sierra's components life is now very good:

```clojure
(ns component.prometheus
  (:require [com.stuartsierra.component :refer [Lifecycle start stop]]
            [clojure.tools.logging :as log]
            [iapetos.core :as metrics]))

(defrecord Prometheus []
  Lifecycle

  (start [component]
    (log/info "Start")
    (-> component
      (assoc :registry ((apply comp (:metrics-collectors component)) metrics/default-registry))))

 (stop [component]
   (log/info "Stop")
   (try
     (metrics/clear (:registry component))
     (catch Exception _))
   (-> component
     (assoc :metrics-collectors nil)
     (assoc :registry nil))))
```

Note the `metrics/default-registry` in the `start`, and the `metrics/clear` in the `stop`. 💯

**Comment by marco-m** [comment]
thanks for the explanation!

**Comment by MalloZup** [comment]
@delitescere  @marco-m @codification . I didn't dive to much on this PR but afaik what stated here: https://github.com/clj-commons/iapetos/pull/12#issuecomment-406118602
make this PR not desirable to merge.

Please correct me if I am wrong thx.

**Comment by MalloZup** [comment]
I'm losing this since is resolved thx!

**Pull request closed without merging**
